name: broka
description: AI-powered marketplace - secure, fair, transparent transactions.
publish_to: none
version: 2.3.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  url_launcher: ^6.2.6
  image_picker: ^1.1.2
  camera: ^0.11.0
  video_player: ^2.8.6
  flutter_tts: ^4.0.2
  audioplayers: ^6.1.0
  speech_to_text: ^6.6.2
  cached_network_image: ^3.3.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  local_auth: ^2.1.8
  flutter_webrtc: ^0.11.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
